// Code generated by protoc-gen-go. DO NOT EDIT.
// source: FoodEvent.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	ProductID            string   `protobuf:"bytes,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	NameBrand            string   `protobuf:"bytes,2,opt,name=NameBrand,proto3" json:"NameBrand,omitempty"`
	IndustryCode         string   `protobuf:"bytes,3,opt,name=IndustryCode,proto3" json:"IndustryCode,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=Role,proto3" json:"Role,omitempty"`
	IndustryName         string   `protobuf:"bytes,5,opt,name=IndustryName,proto3" json:"IndustryName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_884d35be91b9b723, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Product) GetNameBrand() string {
	if m != nil {
		return m.NameBrand
	}
	return ""
}

func (m *Product) GetIndustryCode() string {
	if m != nil {
		return m.IndustryCode
	}
	return ""
}

func (m *Product) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Product) GetIndustryName() string {
	if m != nil {
		return m.IndustryName
	}
	return ""
}

type Consumer struct {
	ConsumerID           string   `protobuf:"bytes,1,opt,name=ConsumerID,proto3" json:"ConsumerID,omitempty"`
	Gender               string   `protobuf:"bytes,2,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Age                  string   `protobuf:"bytes,3,opt,name=Age,proto3" json:"Age,omitempty"`
	AgeUnit              string   `protobuf:"bytes,4,opt,name=AgeUnit,proto3" json:"AgeUnit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Consumer) Reset()         { *m = Consumer{} }
func (m *Consumer) String() string { return proto.CompactTextString(m) }
func (*Consumer) ProtoMessage()    {}
func (*Consumer) Descriptor() ([]byte, []int) {
	return fileDescriptor_884d35be91b9b723, []int{1}
}

func (m *Consumer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consumer.Unmarshal(m, b)
}
func (m *Consumer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consumer.Marshal(b, m, deterministic)
}
func (m *Consumer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consumer.Merge(m, src)
}
func (m *Consumer) XXX_Size() int {
	return xxx_messageInfo_Consumer.Size(m)
}
func (m *Consumer) XXX_DiscardUnknown() {
	xxx_messageInfo_Consumer.DiscardUnknown(m)
}

var xxx_messageInfo_Consumer proto.InternalMessageInfo

func (m *Consumer) GetConsumerID() string {
	if m != nil {
		return m.ConsumerID
	}
	return ""
}

func (m *Consumer) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Consumer) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *Consumer) GetAgeUnit() string {
	if m != nil {
		return m.AgeUnit
	}
	return ""
}

type FoodEvent struct {
	FoodEventID          string     `protobuf:"bytes,1,opt,name=FoodEventID,proto3" json:"FoodEventID,omitempty"`
	Reactions            []string   `protobuf:"bytes,2,rep,name=Reactions,proto3" json:"Reactions,omitempty"`
	ReportNumber         int64      `protobuf:"varint,3,opt,name=ReportNumber,proto3" json:"ReportNumber,omitempty"`
	Outcomes             []string   `protobuf:"bytes,4,rep,name=Outcomes,proto3" json:"Outcomes,omitempty"`
	Products             []*Product `protobuf:"bytes,5,rep,name=Products,proto3" json:"Products,omitempty"`
	DateCreated          string     `protobuf:"bytes,6,opt,name=DateCreated,proto3" json:"DateCreated,omitempty"`
	DateStarted          string     `protobuf:"bytes,7,opt,name=DateStarted,proto3" json:"DateStarted,omitempty"`
	Consumer             *Consumer  `protobuf:"bytes,8,opt,name=Consumer,proto3" json:"Consumer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FoodEvent) Reset()         { *m = FoodEvent{} }
func (m *FoodEvent) String() string { return proto.CompactTextString(m) }
func (*FoodEvent) ProtoMessage()    {}
func (*FoodEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_884d35be91b9b723, []int{2}
}

func (m *FoodEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodEvent.Unmarshal(m, b)
}
func (m *FoodEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodEvent.Marshal(b, m, deterministic)
}
func (m *FoodEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodEvent.Merge(m, src)
}
func (m *FoodEvent) XXX_Size() int {
	return xxx_messageInfo_FoodEvent.Size(m)
}
func (m *FoodEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodEvent.DiscardUnknown(m)
}

var xxx_messageInfo_FoodEvent proto.InternalMessageInfo

func (m *FoodEvent) GetFoodEventID() string {
	if m != nil {
		return m.FoodEventID
	}
	return ""
}

func (m *FoodEvent) GetReactions() []string {
	if m != nil {
		return m.Reactions
	}
	return nil
}

func (m *FoodEvent) GetReportNumber() int64 {
	if m != nil {
		return m.ReportNumber
	}
	return 0
}

func (m *FoodEvent) GetOutcomes() []string {
	if m != nil {
		return m.Outcomes
	}
	return nil
}

func (m *FoodEvent) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *FoodEvent) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *FoodEvent) GetDateStarted() string {
	if m != nil {
		return m.DateStarted
	}
	return ""
}

func (m *FoodEvent) GetConsumer() *Consumer {
	if m != nil {
		return m.Consumer
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "v1.Product")
	proto.RegisterType((*Consumer)(nil), "v1.Consumer")
	proto.RegisterType((*FoodEvent)(nil), "v1.FoodEvent")
}

func init() { proto.RegisterFile("FoodEvent.proto", fileDescriptor_884d35be91b9b723) }

var fileDescriptor_884d35be91b9b723 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0x6a, 0xf3, 0x30,
	0x10, 0xc5, 0xb1, 0x9d, 0x3f, 0xce, 0x38, 0xf0, 0x7d, 0xcc, 0xa2, 0x88, 0x52, 0x8a, 0xf1, 0xa6,
	0x5e, 0x05, 0x92, 0x9e, 0x20, 0x4d, 0xda, 0x92, 0x4d, 0x5a, 0x54, 0x7a, 0x00, 0x27, 0x1a, 0x42,
	0xa0, 0x96, 0x82, 0x2c, 0x07, 0x7a, 0x9c, 0xf6, 0xa4, 0x45, 0x8e, 0xac, 0xd8, 0xbb, 0x99, 0xdf,
	0x1b, 0x69, 0x9e, 0x9f, 0x05, 0xff, 0x5e, 0x94, 0x12, 0xcf, 0x67, 0x92, 0x66, 0x76, 0xd2, 0xca,
	0x28, 0x0c, 0xcf, 0xf3, 0xec, 0x27, 0x80, 0xf1, 0xbb, 0x56, 0xa2, 0xde, 0x1b, 0xbc, 0x83, 0x89,
	0x2b, 0x37, 0x6b, 0x16, 0xa4, 0x41, 0x3e, 0xe1, 0x57, 0x60, 0xd5, 0x6d, 0x51, 0xd2, 0x93, 0x2e,
	0xa4, 0x60, 0xe1, 0x45, 0xf5, 0x00, 0x33, 0x98, 0x6e, 0xa4, 0xa8, 0x2b, 0xa3, 0xbf, 0x57, 0x4a,
	0x10, 0x8b, 0x9a, 0x81, 0x1e, 0x43, 0x84, 0x01, 0x57, 0x5f, 0xc4, 0x06, 0x8d, 0xd6, 0xd4, 0xdd,
	0x73, 0xf6, 0x32, 0x36, 0xec, 0x9f, 0xb3, 0x2c, 0x93, 0x10, 0xaf, 0x94, 0xac, 0xea, 0x92, 0x34,
	0xde, 0x03, 0xb4, 0xb5, 0x37, 0xd9, 0x21, 0x78, 0x03, 0xa3, 0x57, 0x92, 0x82, 0xb4, 0xb3, 0xe8,
	0x3a, 0xfc, 0x0f, 0xd1, 0xf2, 0xd0, 0xda, 0xb2, 0x25, 0x32, 0x18, 0x2f, 0x0f, 0xf4, 0x29, 0x8f,
	0xc6, 0x19, 0x6a, 0xdb, 0xec, 0x37, 0x84, 0x89, 0xcf, 0x0a, 0x53, 0x48, 0x7c, 0xe3, 0x57, 0x76,
	0x91, 0x4d, 0x86, 0x53, 0xb1, 0x37, 0x47, 0x25, 0x2b, 0x16, 0xa6, 0x91, 0x4d, 0xc6, 0x03, 0xfb,
	0x85, 0x9c, 0x4e, 0x4a, 0x9b, 0x6d, 0x5d, 0xee, 0x48, 0x37, 0x16, 0x22, 0xde, 0x63, 0x78, 0x0b,
	0xf1, 0x5b, 0x6d, 0xf6, 0xaa, 0xa4, 0x8a, 0x0d, 0x9a, 0x0b, 0x7c, 0x8f, 0x0f, 0x10, 0xbb, 0x9f,
	0x50, 0xb1, 0x61, 0x1a, 0xe5, 0xc9, 0x22, 0x99, 0x9d, 0xe7, 0x33, 0xc7, 0xb8, 0x17, 0xad, 0xd1,
	0x75, 0x61, 0x68, 0xa5, 0xa9, 0x30, 0x24, 0xd8, 0xe8, 0x62, 0xb4, 0x83, 0xda, 0x89, 0x0f, 0x53,
	0x68, 0x3b, 0x31, 0xbe, 0x4e, 0x38, 0x84, 0xf9, 0x35, 0x6a, 0x16, 0xa7, 0x41, 0x9e, 0x2c, 0xa6,
	0x76, 0x59, 0xcb, 0xb8, 0x57, 0x77, 0xa3, 0xe6, 0x0d, 0x3d, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff,
	0x4e, 0x8a, 0xff, 0x4a, 0x56, 0x02, 0x00, 0x00,
}
